import React from 'react'

export default function Home() {
  return (
    <>
    <section className='home z-5 font-montserrat text-uppercase lg:m-5 m-[1rem] sm:m-[1rem] bg-dark text-white rounded-[15px] lg:rounded-[36px] sm:rounded-[15px] shadow-[0_5px_30px_-5px_rgba(0,0,0,0.3)] p-4 lg:p-5 sm:p-4'>
      <div className='about-weather mb-3'>
        <h1 className='text-3xl font-medium tracking-normal lg:tracking-wide sm:tracking-normal'>About Weather</h1>
      </div>
      <div className='about-para text-[#fff] font-bold leading-[36px] mt-7 tracking-wider'>
          <ul className='list-disc m-3 lg:m-3 md:m-3 sm:m-1'>
            <li>
            <p>Weather is the day-to-day state of the atmosphere in a region and its short-term (minutes to weeks) variations, whereas climate is defined as statistical weather information that describes the variation of weather at a given place for a specified interval. They are both used interchangeably sometimes but differ in terms of the length of time they measure and what trends affect them.</p>
            </li>
            <li>
            <p className='mt-3'>Weather is the combination of temperature, humidity, precipitation, cloudiness, visibility, and wind. In popular usage, climate represents the synthesis of weather; more formally, it is the weather of a locality averaged over some period (usually 30 years), plus statistics of weather extremes.</p>
            </li>
          </ul>
      </div>
    </section>
    <div className='row flex justify-center items-center mx-auto'>
      <div className='col-lg-12'>
      <table className='table table-striped table-bordered table-success mt-5 xl:mt-0 lg:mt-0 sm:mt-5 text-black font-md w-full'>
      <tbody>
        <tr className='font-bold text-center'>
          <td>Basis of Difference</td>
          <td>Climate</td>
          <td>Weather</td>
        </tr>
        <tr className=''>
          <td>Definition</td>
          <td>Describes the average conditions expected at a specific place at a given time.A region's climate is generated by the climate system, which has five components: atmosphere, hydrosphere, cryosphere, land surface, and biosphere.</td>
          <td>Describes the atmospheric conditions at a specific place at a specific point in time. Weather generally refers to day-to-day temperature and precipitation activity</td>
        </tr>
        <tr>
          <td>Components</td>
          <td>Climate may include precipitation, temperature, humidity, sunshine, wind velocity, phenomena such as fog, frost, and hail storms over a long period of time.</td>
          <td>Weather includes sunshine, rain, cloud cover, winds, hail, snow, sleet, freezing rain, flooding, blizzards, ice storms, thunderstorms, steady rains from a cold front or warm front, excessive heat, heat waves and more</td>
        </tr>
        <tr>
          <td>Forecast</td>
          <td>By aggregates of weather statistics over periods of 30 years</td>
          <td>By collecting meteorological data, like air temperature, pressure, humidity, solar radiation, wind speeds and direction etc.</td>
        </tr>
        <tr>
          <td>Determining factors</td>
          <td>Aggregating weather statistics over periods of 30 years ("climate normals").</td>
          <td>Real-time measurements of atmospheric pressure, temperature, wind speed and direction, humidity, precipitation, cloud cover, and other variables</td>
        </tr>
      </tbody>
    </table>
      </div>
    </div>
    </>
  )
}
